#!/bin/bash

# TODO: Remove this later and set this based on eeprom results
if [ -f /sys/class/i2c-dev/i2c-1/device/1-0034/name ]; then
	keypad=$(cat /sys/class/i2c-dev/i2c-1/device/1-0034/name)

	if [[ $keypad = *"tca8418"* ]]
   	    then
		export POCKETCHIP=true
	else
		export POCKETCHIP=false
	fi
fi

function setPocketchip {
	if [ ! -f /sys/class/gpio/gpio114/direction ]; then
		echo 114 > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio114/direction	
		echo 1 > /sys/class/gpio/gpio114/value

		echo 0 > /sys/class/pwm/pwmchip0/export
		echo 1 > /sys/class/pwm/pwmchip0/pwm0/enable
		echo 1000000 > /sys/class/pwm/pwmchip0/pwm0/period
		echo 1000000 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
	fi

        local KEYBOARD_MAP='/usr/local/share/kbd/keymaps/pocketChip.map'
        local DEFAULT_MAP='/home/chip/.Xmodmap'

        # Check if we're running on PocketCHIP
        if [[ $POCKETCHIP == true ]]; then
                if [ ! -f $DEFAULT_MAP ]; then #Make sure a default keymap isn't already set
                        # Create symbolic link from the PocketCHIP keymap to the default xmodmap
                        ln -s "$KEYBOARD_MAP" "$DEFAULT_MAP"
                fi
        else
                # Compare PocketCHIP keyboard map to default one.
                # If they're the same, remove symbolic link since we are not on PocketCHIP
                if [[ -f $DEFAULT_MAP && 'stat -c%s "$KEYBOARD_MAP"'=='stat -c%s "$DEFAULT_MAP"' ]]; then
                        rm $DEFAULT_MAP
                fi
        fi
	
	while [ -f /sys/class/gpio/gpio114/direction ]; do
                enable=$(cat /sys/class/gpio/gpio114/value)
                screen=$(XAUTHORITY=/home/chip/.Xauthority DISPLAY=:0 xset q | grep "is O")
                if [[ $screen = *"is Of"* ]]; then
                        if [[ $enable = "1" ]]; then
                                echo 0 > /sys/class/gpio/gpio114/value
                        fi
                        sleep 0.5
                else
                        if [[ $enable = "0" ]]; then
                                echo 1 > /sys/class/gpio/gpio114/value
                        fi
                        sleep 5
                fi
	done
}  

(sleep 10s ; \
setPocketchip )&

exit 0
