#!/bin/bash

export POCKETCHIP=true

function setPocketchip {
	DISPLAY=:0 XAUTHORITY=${HOME}/.Xauthority xmodmap ${HOME}/.Xmodmap 2> /dev/null

	STATUS="$?"
	if [ "$STATUS" != "0" ] ; then
		while [ "$STATUS" != "0" ] ; do
			DISPLAY=:0 XAUTHORITY=${HOME}/.Xauthority xmodmap ${HOME}/.Xmodmap 2> /dev/null
			STATUS="$?"
			sleep 1
		done
	fi
	brightness=$(cat /sys/class/backlight/backlight/brightness)
	
	while [ -f /sys/class/backlight/backlight/brightness ]; do
                currentBrightness=$(cat /sys/class/backlight/backlight/brightness)
                screen=$(XAUTHORITY=${HOME}/.Xauthority DISPLAY=:0 xset q 2> /dev/null | grep "is O")
                if [[ $screen = *"is Of"* ]]; then
                        if [[ $currentBrightness != "0" ]]; then
				currentBrightness = 0
				brightness=$(cat /sys/class/backlight/backlight/brightness)
                           	echo 0 > /sys/class/backlight/backlight/brightness
                        fi
                        sleep 0.5
                else
                        if [[ $currentBrightness = "0" ]]; then
                                echo $brightness > /sys/class/backlight/backlight/brightness
                        fi
                        sleep 5
                fi
	done
}  

setPocketchip & 

exit 0
