#!/bin/bash

function setPocketchip {
        local KEYBOARD_MAP='/usr/local/share/kbd/keymaps/pocketChip.map'
        local DEFAULT_MAP='/home/chip/.Xmodmap'

        # Check if we're running on PocketCHIP
        if [[ $POCKETCHIP == true ]]; then
                if [ ! -f $DEFAULT_MAP ]; then #Make sure a default keymap isn't already set
                        # Create symbolic link from the PocketCHIP keymap to the default xmodmap
                        ln -s "$KEYBOARD_MAP" "$DEFAULT_MAP"
                fi
        else
                # Compare PocketCHIP keyboard map to default one.
                # If they're the same, remove symbolic link since we are not on PocketCHIP
                if [[ -f $DEFAULT_MAP && 'stat -c%s "$KEYBOARD_MAP"'=='stat -c%s "$DEFAULT_MAP"' ]]; then
                        rm $DEFAULT_MAP
                fi
        fi

	brightness=$(cat /sys/class/backlight/backlight/brightness)
	
	while [ -f /sys/class/backlight/backlight/brightness ]; do
                currentBrightness=$(cat /sys/class/backlight/backlight/brightness)
                #echo $currentBrightness
                screen=$(XAUTHORITY=/home/chip/.Xauthority DISPLAY=:0 xset q | grep "is O")
                if [[ $screen = *"is Of"* ]]; then
                        if [[ $currentBrightness != "0" ]]; then
				currentBrightness = 0
				brightness=$(cat /sys/class/backlight/backlight/brightness)
                           	echo 0 > /sys/class/backlight/backlight/brightness
                        fi
                        sleep 0.5
                else
                        if [[ $currentBrightness = "0" ]]; then
                                echo $brightness > /sys/class/backlight/backlight/brightness
                        fi
                        sleep 5
                fi
	done
}  

(sleep 5s ; \
setPocketchip )&

exit 0
